### ISSUE TITLE
Debug in Visual Studio 2019 with Docker-Compose Fails

### ISSUE THREAD

**Issue by tylerje** [microsoft/TailwindTraders-Backend#97]
I have the Cosmos DB Emulator installed and working properly (verified by testing with other code), but when I try to run the backend with VS debugger, I get this error during startup on the Profile api project in the Main method. I've tried with and without a .env file configured as noted in the readme text. I'm running the latest VS 2019, latest Docker for Windows with WSL 2 and Ubuntu distro. Do I need to abandon WSL2 and use Hyper-V with additional RAM allocated as indicated in a previous issue similar to this?

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Connection refused)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Tailwind.Traders.Profile.Api.Program.<>c.<Main>b__0_0(ProfileContext context, IServiceProvider services) in D:\Code\Github\TailwindTraders-Backend\Source\Services\Tailwind.Traders.Profile.Api\Program.cs:line 21
   at Tailwind.Traders.Profile.Api.Extensions.WebHostExtensions.MigrateDbContext[TContext](IWebHost webHost, Action`2 seeder) in D:\Code\Github\TailwindTraders-Backend\Source\Services\Tailwind.Traders.Profile.Api\Extensions\WebHostExtensions.cs:line 20
   at Tailwind.Traders.Profile.Api.Program.Main(String[] args) in D:\Code\Github\TailwindTraders-Backend\Source\Services\Tailwind.Traders.Profile.Api\Program.cs:line 14

  This exception was originally thrown at this call stack:
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
    System.Net.Http.ConnectHelper.ConnectAsync(string, int, System.Threading.CancellationToken)

Inner Exception 1:
HttpRequestException: Connection refused

Inner Exception 2:
SocketException: Connection refused

**Comment by borjasanes** [comment]
If you have any questions, please reopen the issue. Thanks!
